import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import { getCurrentUser } from '@/lib/fetch-client';
import Header from '@/components/header';

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const { currentUser } = await getCurrentUser();

  return (
    <html lang='en'>
      <body>
        <Header currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
